apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: asabbar-app
  namespace: argocd

spec:
  destination:
    namespace: dev
    server: https://kubernetes.default.svc
  project: default
  source:
    repoURL: https://github.com/a-sabbar/inception_rep
    targetRevision: master
    path: .
  syncPolicy:
    automated:
      prune: true
      selfHeal: true