apiVersion: v1
kind: Secret
metadata:
  name: my-repo-secret
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  url: https://github.com/a-sabbar/inception_rep
  username: a-sabbar
  password: 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