
Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/xenial64" 
  
  config.vm.define "Server" do |server|
    server.vm.hostname = "asabbarS"
    server.vm.network "private_network", ip: "192.168.56.110"
    server.vm.provider "virtualbox" do |vb|
      vb.name = "asabbarS"
      vb.memory = "1024"
      vb.cpus = 1
    end
    server.vm.provision "shell", inline: <<-SHELL
      echo '* * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *'
      echo 'Running provision server script...' 
      echo 'Installing K3s on the server...'
      curl -sfL https://get.k3s.io | sh -
    SHELL
  end
end

