
Vagrant.configure("2") do |config|
  config.vm.box = "bento/ubuntu-24.04"
  
  config.vm.define "Server" do |server|
    server.vm.hostname = "asabbarS"
    server.vm.network "private_network", ip: "192.168.56.110"
    server.vm.provider "virtualbox" do |vb|
      vb.name = "asabbarS"
      vb.memory = "1024"
      vb.cpus = 1
    end
    server.vm.provision "shell", inline: <<-SHELL
      echo '* * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *'
      echo 'Running provision server script...' 
      echo 'Installing K3s on the server...'
      curl -sfL https://get.k3s.io | sh -
      echo '* * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *'
      echo 'Copying the node-token to the shared folder...'
      sudo cat /var/lib/rancher/k3s/server/node-token > /vagrant/node-token
      sudo chmod 777 /vagrant/node-token
    SHELL
    
  end
  
  config.vm.define "ServerWorker" do |worker|
    worker.vm.box = "bento/ubuntu-24.04"

    worker.vm.hostname = "asabbarSW"
    worker.vm.network "private_network", ip: "192.168.56.111"
    worker.vm.provider "virtualbox" do |vb|
      vb.name = "asabbarSW"
      vb.memory = "1024"
      vb.cpus = 1
    end
    worker.vm.provision "shell", inline: <<-SHELL
    echo '* * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *'
      echo 'Running provision worker script...'
      echo 'Installing K3s on the worker...'
      curl -sfL https://get.k3s.io | K3S_URL=https://192.168.56.110:6443 K3S_TOKEN=$(cat /vagrant/node-token) sh -
    SHELL
    

  end
end

